version: '3.8'

services:
  # Next.js Application
  app:
    build: .
    container_name: videosn8n-app
    restart: unless-stopped
    ports:
      - "3030:3000"
    environment:
      # Database (External PostgreSQL)
      DATABASE_URL: ${DATABASE_URL}
      
      # NextAuth
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      
      # n8n Integration
      N8N_BASE_URL: ${N8N_BASE_URL}
      N8N_WEBHOOK_SEND_APPROVAL: ${N8N_WEBHOOK_SEND_APPROVAL}
      
      # BLOTATO API
      BLOTATO_API_KEY: ${BLOTATO_API_KEY}
      
      # App Config
      NODE_ENV: production
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s